In [1]:
import numpy as np
import ot
import os,sys
sys.path.append(os.path.realpath('../lib'))

In [62]:
np.random.seed(8)
xalea = np.random.randn(10, 2)
C1 = ot.dist(xalea, xalea)
C1=
C2=C1
p=np.ones(C1.shape[0])/C1.shape[0]
q=p

In [63]:
#from ot.gromov import init_matrix,tensor_product
from FGW import init_matrix,tensor_product

In [64]:
Gc=np.eye(C1.shape[0])/C1.shape[0]

In [65]:
#Gc=p[:,None]*q[None,:]

In [66]:
Gc

array([[0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1]])

In [67]:
#constC,hC1,hC2=init_matrix(C1,C2,np.outer(p,q),p,q)
constC,hC1,hC2=init_matrix(C1,C2,p,q)
tens=tensor_product(constC,hC1,hC2,Gc)

In [68]:
N=tens.shape[0]

In [69]:
tens2 = np.zeros((N,N))

In [70]:
for i in range(N):
    for j in range(N):
        for k in range(N):
            for l in range(N):
                A=(C1[i,k]-C2[j,l])**2
                tens2[i,j] += A*(Gc[k,l])

In [71]:
tens

array([[-7.10542736e-15,  1.08025158e+02,  8.62377810e+01,
         7.15012770e+01,  3.91613371e+00,  1.67642932e+01,
         3.57283359e+01,  2.82473513e+01,  1.57380366e+01,
         1.18568655e+01],
       [ 1.08025158e+02, -5.68434189e-14,  9.59699702e+01,
         1.92628745e+02,  1.16665842e+02,  9.42838579e+01,
         2.62890824e+01,  3.88462266e+01,  7.96200976e+01,
         6.59022966e+01],
       [ 8.62377810e+01,  9.59699702e+01,  0.00000000e+00,
         9.59515909e+01,  9.64708469e+01,  3.01338752e+01,
         9.27762068e+01,  1.10217821e+02,  1.18681172e+02,
         1.09556054e+02],
       [ 7.15012770e+01,  1.92628745e+02,  9.59515909e+01,
         5.68434189e-14,  4.89331931e+01,  7.33544548e+01,
         1.45036994e+02,  1.27287779e+02,  7.39164810e+01,
         1.08491735e+02],
       [ 3.91613371e+00,  1.16665842e+02,  9.64708469e+01,
         4.89331931e+01,  0.00000000e+00,  2.71529455e+01,
         4.61861204e+01,  3.30912143e+01,  9.92846599e+00,
         1.

In [72]:
tens2

array([[  0.        , 108.02515796,  86.23778104,  71.50127696,
          3.91613371,  16.76429323,  35.72833592,  28.24735127,
         15.73803659,  11.85686546],
       [108.02515796,   0.        ,  95.96997017, 192.62874457,
        116.66584208,  94.28385786,  26.28908245,  38.84622659,
         79.62009757,  65.90229664],
       [ 86.23778104,  95.96997017,   0.        ,  95.95159091,
         96.47084693,  30.13387521,  92.77620679, 110.2178206 ,
        118.68117234, 109.55605387],
       [ 71.50127696, 192.62874457,  95.95159091,   0.        ,
         48.9331931 ,  73.35445484, 145.03699372, 127.28777876,
         73.91648099, 108.49173543],
       [  3.91613371, 116.66584208,  96.47084693,  48.9331931 ,
          0.        ,  27.15294554,  46.18612043,  33.09121435,
          9.92846599,  16.51589714],
       [ 16.76429323,  94.28385786,  30.13387521,  73.35445484,
         27.15294554,   0.        ,  44.66939843,  49.69798966,
         48.10721937,  37.25394406],
       [ 3